version: '3.8'

services:
  rabbitMQ:
    image: rabbitmq:3.10.5-management
    container_name: rabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: 'castilhoRBMQ'
      RABBITMQ_DEFAULT_PASS: 'castilhoRBMQ'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq_datal:/var/lib/rabbitmq
      - rabbitmq_log:/var/lib/rabbitmq

volumes:
  rabbbitmq_data:
  rabbitmq_log: